language: ruby
rvm:
  - jruby-19mode
  - jruby-head
jdk:
  - oraclejdk7
  - oraclejdk8
script:
 - rake new_ci
env:
  - MIRAH_TEST_JVM_VERSION=1.5
  - MIRAH_TEST_JVM_VERSION=1.6
  - MIRAH_TEST_JVM_VERSION=1.7
  - MIRAH_TEST_JVM_VERSION=1.8
notifications:
  irc: "irc.freenode.org#mirah"
matrix:
  allow_failures:
    - rvm: jruby-head
  exclude:
    - jdk: oraclejdk7
      env: MIRAH_TEST_JVM_VERSION=1.8